# Generated by Django 5.2.4 on 2025-07-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TodoItem',
        ),
    ]
