# Generated by Django 5.2.4 on 2025-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_task_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['session_key'], name='todo_app_to_session_50729c_idx'),
        ),
    ]
